main.go

Respect the given filename and get the absolute path
fixes #9

fixing output filepath from ZIP file

---

README.md
main.go
modules/grafana/collector.go
modules/grafana/collector_test.go

Extension by the module-grafana.
The following data is collected:
* Configuration from /etc/grafana & /usr/share/grafana
* Package versions 
* Service status
* grafana-cli version
* grafana-cli plugins list
See [modules/grafana/collector.go](modules/grafana/collector.go) for details.

Add module grafana

---

README.md
main.go
modules/postgresql/collector.go
modules/postgresql/collector_test.go

Feature request for module-postgreSQL.
The following data is collected:
* Package versions
* Service status
* Configuration files from `/etc/postgresql` and `/var/lib/pgsql`
For this module no obfuscation is necessary.
See [modules/postgresql/collector.go](modules/postgresql/collector.go) for details.

Add PostgreSQL module

---

README.md
modules/icinga2/collector.go

Extension of the Icinga 2 module with check plugins.
Files:
* `/usr/lib64/nagios/plugins`
Packages:
* `netways-plugin*`
* `monitoring-plugin*`
* `nagios-plugin*`

Icinga2: Add PluginDir in files and plugins in packages

---

main.go

Append hostname to filename to better identify files.
Example:
psupport-ic01-netways-support-20220523-0632.zip
Review needed.

append hostname to filename

---

README.md
main.go
modules/icingadb/collector.go
modules/icingadb/collector_test.go

Add module for IcingaDB
Following data is collected:
* Configuration from `/etc/icingadb`, `/etc/icingadb-redis` and `/etc/icinga2/features-enabled/icingadb.conf`
* Service status from `icingadb`, `icingadb-redis` and `icingadb-redis-server`
* Package information
* Journal logs from `icingadb`, `icingadb-redis` and `icingadb-redis-server`
Thoughts? @pdorschner

add module icingadb

---

modules/puppet/collector.go

Replace version source to facter.
facter is installed by default with every puppet installation. This allows a deeper insight into the puppet information.

puppet: change version source to facter

---

.golangci.yml
main.go
modules/icingaweb2/collector.go
pkg/collection/file.go
pkg/util/testing.go
version.go

Replace io/ioutil with os, because io/ioutil is deprecated since go 1.16

replace ioutil with os

---

README.md
modules/postgresql/collector.go

add postgresql version using `psql -V`

postgresql: add version

---

modules/icinga2/collector.go
modules/icingadb/collector.go
modules/mysql/collector.go

Collect logrotate from icinga2, icingadb and mysql/mariadb

collect logrotate

---

main.go
modules/corosync/collector.go
modules/corosync/collector_test.go
modules/corosync/testdata/etc/corosync/corosync.conf
modules/corosync/testdata/etc/corosync/service.d/pcmk
modules/corosync/testdata/var/lib/pacemaker/cib/cib.xml

- Since both tools are usually deployed side-by-side we gather them in one collector
Fixes #25

Add corosync/pacemaker collector

---

modules/base/collector.go

Collect `iotop` and `ioping` in module base
Fixes #57

base: collect io stats

---

modules/corosync/collector.go

The current '/etc/corosync/service.d' path is not mandatory. Better use '/etc/corosync' instead

corosync: adjust relevant path

---

modules/ansible/collector.go
modules/base/collector.go
modules/corosync/collector.go
modules/grafana/collector.go
modules/graphite/collector.go
modules/icinga2/collector.go
modules/icingadb/collector.go
modules/icingadirector/collector.go
modules/icingaweb2/collector.go
modules/influxdb/collector.go
modules/keepalived/collector.go
modules/mysql/collector.go
modules/postgresql/collector.go
modules/puppet/collector.go

To avoid errors like XYZ, it makes more sense to build the paths of the files using filepath.Join()
https://pkg.go.dev/path/filepath#Join

adjust file paths

---

.golangci.yml
modules/icinga2/collector.go
modules/icinga2/collector_test.go
modules/icinga2/testdata/icinga-version.txt

To get the current state in `icinga2 object list` it is necessary to build the icinga2.debug since 2.14.0.  
This is done with `icinga2 daemon -C --dump-objects`
fixes #93

build icinga2.debug if Icinga 2 version >= 2.14

---

README.md
go.mod
go.sum
main.go
modules/foreman/collector.go
modules/foreman/collector_test.go
modules/foreman/testdata/etc/foreman/database.yml
modules/foreman/testdata/etc/foreman/database.yml.obfuscated
modules/foreman/testdata/etc/foreman/encryption_key.rb
modules/foreman/testdata/etc/foreman/encryption_key.rb.obfuscated

Adds module for foreman.
fixes #51

add module foreman

---

main.go
modules/graphite/collector.go
modules/icinga2/collector.go
modules/icingaweb2/collector.go
pkg/collection/collection.go

The tool works according to the "we get what we can" principle. If it doesn't find something, which is perfectly possible and okay, no warnings should be thrown.
A detailed log of the commands not executed or the files not found can be found in the run log itself.

change logging verbosity

---

internal/collection/collection.go
modules/icinga2/api.go

Json was not formatted properly in the output.

fix json formatting

---

.github/workflows/golangci-lint.yml
.golangci.yml
go.mod
go.sum
internal/obfuscate/obfuscate.go
modules/icinga2/collector.go
modules/icingadirector/collector.go

This PR should add configuration that's sent to the local node. This should collect configuration on every kind of Icinga 2 node including configuration that is managed by Director or via API.
Please take into account, that I'm totally new to the code of this tool. Don't expect that I know what I'm doing.

Add synced config to Icinga 2 module

---

.golangci.yml
internal/collection/collection.go
internal/metrics/metrics.go
main.go
modules/icinga2/collector.go
version.go

Introduce metrics about the collection.
* How is the command called? (Values from \*--icinga2\* are obfuscated)
* Move timings from timing.yml to metrics
* Version
Metrics will be saved to metrics.json
```
{"command":"/home/ubuntu/support-collector/executables-Gbx8dzGyfT/___go_build_github_com_NETWAYS_support_collector_linux --icinga2-api-user \u003cHIDDEN\u003e --icinga2-api-pass \u003cHIDDEN\u003e --icinga2-api-endpoints \u003cHIDDEN\u003e --enable webservers","version":"0.10.1","timings":{"total":32594129,"webservers":32254571}}
```

Introduce run metrics

---

main.go

The condition of the dependency function for the `icinga2` is not correct. It should only match if exactly `icinga2` or `all` has been given.

Fix wizard dependency for icinga2

---

internal/config/wizard.go

`StringSliceVar` should respect whitespaces in the comma seperated list.

Respect whitespaces in wizard StringSliceVar

---

modules/icingadb/collector.go

Obfuscator is not matching for passwords in icingadb.yml

Obfuscate icingadb.yml passwords

---

modules/icingadb/collector.go
modules/redis/collector.go

We fetch in this PR information about the value of **overcommit_memory** on system which is relevant for icingadb/redis module.
fixes #134

fetch system overcommit_memory
