main.go
variable passing from the Timeout Duration added.
Already tested!
The argument --command-timeout now also works
=> Add timeout override

README.md, modules/base/collector.go
* /etc/apt/sources.list
* /etc/apt/sources.list.d
* /etc/yum.repos.d/
* /etc/zypp/repos.d/
=> Add repositories to the base module

README.md, main.go, modules/influxdb/collector.go, modules/influxdb/collector_test.go
Feature request for module-influxDB.
The following data is collected:
* Configuration file from `/etc/influxdb/config.*`
* Package versions
* Service status
For this module no obfuscation is necessary.
See [modules/influxdb/collector.go](modules/influxdb/collector.go) for details.
=>  Add InfluxDB module

README.md, go.mod, go.sum, main.go, modules/graphite/collector.go, modules/graphite/collector_test.go, pkg/collection/processes.go, pkg/util/util.go
Feature request for module-graphite.
The following data is collected:
* Configuration from:
* `/opt/graphite/conf`,
* `/opt/graphite/bin`,
* `/opt/graphite/webapp/graphite/local_settings.py`,
* `/var/log/carbon`,
* Package versions
* Python and pip version & list
* Process list for `*graphite*` and `*carbon`
A obfuscation for `.conf` and `.py` files was built in
See [modules/graphite/collector.go](modules/graphite/collector.go) for details.
=> Add Graphite module

.golangci.yml, modules/base/collector.go, modules/icinga2/collector.go, modules/icingadirector/collector.go, modules/icingaweb2/collector.go, modules/mysql/collector.go, modules/postgresql/collector.go, pkg/collection/collection.go, pkg/collection/services.go
Issue #30
For more details about Daemons, I have added the following information:
* systemd startup files
* tmpfiles.d config for vspehredb
* journal logs for services
* user permissions and groups
Please review @pdorschner and @dgoetz
=> Add some daemon infos

modules/icinga2/collector.go
Extension for module icinga2
* add systemd startup file
* add user information
Review needed.
=> extension for module icinga2

modules/icingadirector/collector.go, modules/icingaweb2/collector.go
Update command for collecting journalctl output.
* only last 7 days are collected now
Review needed.
=> add timestamp for journalctl

modules/puppet/collector.go
Extension for puppet module
* Add `/opt/puppetlabs/puppet/cache` to files
Review needed.
=> extension for puppet module

README.md, modules/mysql/collector.go
Add mysql version using `mysql -V`
=> mysql: add version

modules/icinga2/collector.go, modules/icingaweb2/collector.go
Move obfuscation for resources.ini from icinga to icingaweb2.
=> fix obfuscation

modules/corosync/collector.go
Adds to module corosync:
* Service status for corosync and pacemaker
* logs for corosync and pacemaker
=> add extended corosync information

modules/keepalived/collector.go
Adds to module keepalived:
* Information about the service
=> keepalived: add extended information

modules/corosync/collector.go, modules/keepalived/collector.go
In module keepalived and corosync the path where the files are stored is incorrect.
=> fix paths for services

.github/workflows/golangci-lint.yml, .golangci.yml
So that the CI doesn't break all the time...
=> Pin golangci-lint Version in CI

modules/icinga2/collector.go
=> [icinga2] Add feature list to collected data

README.md, main.go, modules/mongodb/collector.go, modules/mongodb/collector_test.go, modules/mongodb/testdata/etc/mongod.conf, modules/mongodb/testdata/etc/mongod.conf.obfuscated
=> Add collector for MongoDB

README.md, main.go, modules/elastic/collector.go, modules/elastic/collector_test.go, modules/elastic/testdata/etc/elasticsearch/elasticsearch.yaml, modules/elastic/testdata/etc/elasticsearch/elasticsearch.yaml.obfuscated, modules/elastic/testdata/etc/elasticsearch/elasticsearch.yml, modules/elastic/testdata/etc/elasticsearch/elasticsearch.yml.obfuscated
=> Add collector for Elastic Stack

README.md, main.go, modules/webservers/collector.go, modules/webservers/collector_test.go
Collector for webservers. Currently only apache2, httpd and nginx
Fixes #83
=> Add webservers collector

README.md, main.go, modules/corosync/collector.go, modules/grafana/collector.go, modules/graphite/collector.go, modules/icinga2/collector.go, modules/icingadb/collector.go, modules/icingadirector/collector.go, modules/icingaweb2/collector.go, modules/influxdb/collector.go, modules/mongodb/collector.go, modules/mysql/collector.go, modules/postgresql/collector.go, modules/puppet/collector.go, modules/webservers/collector.go, pkg/collection/collection.go, pkg/util/util.go
By default, we should not collect all possible information for security reasons and the amount of data collected.
=> add detailed collection

README.md, modules/icinga2/collector.go
Collect data about the [icinga-installer](https://github.com/NETWAYS/icinga-installer)
fixes #95
=> add-icinga-installer

.github/workflows/go.yml, .goreleaser.yml
Fixes #101 
```
goreleaser release --snapshot --rm-dist
• starting release...
cat dist/checksums.txt 
284ad695b904f2c793fb4b6b05ceb726f371c472a7289948a546d7a5960f77d5  
support-collector-x86_64Linux
```
=> Fix goreleaser config

README.md, internal/collection/collection.go, internal/collection/file.go
Avoid collecting of sensitive files.
fixes #118
=> ignore sensitive files in collection

.github/workflows/go.yml, .goreleaser.yml
Update goreleaser for current version
=> update goreleaser for v2

README.md, main.go, modules/redis/collector.go, modules/redis/collector_test.go, modules/redis/testdata/etc/redis.conf, modules/redis/testdata/etc/redis.conf.obfuscated
=> Add module redis

internal/config/wizard.go, main.go
=> Add obfuscators to wizard
